[[main]]
    identifier = 'home'
    name = 'home 首页'
    url = '/'
    pageRef = '/'
    weight = 1
[[main]]
    identifier = 'about-us'
    name = 'about us 简介'
    url = '/about-us'
    pageRef = '/about-us'
    weight = 2
[[main]]
    identifier = 'brand'
    name = 'brand 品牌'
    url = '/brand'
    pageRef = '/brand'
    weight = 3
[[main]]
    identifier = 'contact-us'
    name = 'contact us 联系我们'
    video = '/contact-us'
    pageRef = '/contact-us'
    weight = 7

