customCSS = ['/css/main.css']
headerJS  = ['https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp', 'https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js']
customJS  = ['https://unpkg.com/siriwave/dist/siriwave.umd.min.js', '/js/main.js']
